import test from 'node:test';
import assert from 'node:assert/strict';
import {makeGame,settleGame} from './harness.mjs';
const plain=x=>JSON.parse(JSON.stringify(x));
function click(w,text){const b=[...w.document.querySelectorAll('#actionSubList [role="button"]')].find(b=>b.textContent.includes(text));assert.ok(b,`Missing ${text}`);b.click();}
function visit(w,id){w.document.getElementById('actionItem-solar').click();w.document.querySelector(`[data-world-id="${id}"]`).click();click(w,'Switch to world');}
function advance(w,target,id='townLaw'){const base=w.chooseEvent;w.chooseEvent=()=>w.planet===target.state.planet?id:null;try{w.nextDay();}finally{w.chooseEvent=base;}}
function propose(w,target,law){const info=w.gameEvents.townLaw,base=info.value,baseCheck=info.check;info.check=(subject,town,args)=>town.name==='Farbank'&&(!baseCheck||baseCheck(subject,town,args));info.value=(subject,town,args)=>{args.result=!w.happen('Legality',subject,town,{law});args.influence=law.split('.')[0];args.name=law.split('.').at(-1).replaceAll('_',' ');return law;};try{advance(w,target);}finally{info.value=base;info.check=baseCheck;}}
function open(w,record){const entry=w.document.querySelector(`[data-story-kind="localChoice"][data-story-id="${record.id}"]`);assert.ok(entry);entry.querySelector('.paultendoChronicleStoryLink').click();return w.document.getElementById('actionSubList');}
function check(g,warnings){assert.deepEqual(g.errors,[]);assert.deepEqual(warnings,[]);}
async function setup(t){const warnings=[];const g=await makeGame({beforeMod:w=>{w.console.warn=(...args)=>warnings.push(args.map(String).join(' '));}});t.after(g.close);const w=g.window,home=settleGame(g);w.planet.day=80;home.pop=100;home.resources={crop:1000};const target=w._paultendoUniverse.worlds[2];target.discovered=target.reached=true;visit(w,2);const at=w.filterChunks(c=>!c.v.s&&c.b!=='water'&&c.b!=='mountain')[0],town=w.happen('Create',null,null,{x:at.x,y:at.y},'town');w.happen('Explore',null,null,{x:at.x,y:at.y});town.name='Farbank';town.start=1;town.pop=40;town.resources={crop:1000,rock:50,cash:500};town.jobs={};town.research={};town.values={justice:0,order:0,openness:0,change:0,wealth:0};for(const k of Object.keys(town.influences))town.influences[k]=0;town._paultendoNextExchangeDay=99999;Object.assign(w.planet.unlocks,{farm:10,travel:10,government:10,smith:20});const original={};for(const [id,e] of Object.entries(w.dailyEvents)){original[id]={func:e.func,perChunk:e.perChunk};if(e.func)e.func=()=>{};if(e.perChunk)e.perChunk=()=>{};}visit(w,1);return {g,w,home,target,town,warnings,original};}

test('a distant food shortage reopens forbidden farming through the native law without granting food or jobs',async t=>{
 const {g,w,target,town,warnings}=await setup(t);town.legal.farm=false;town.resources.crop=0;advance(w,target);assert.equal(town.legal.farm,true);assert.equal(town.resources.crop,0);assert.deepEqual(plain(town.jobs),{});const record=target.state.planet._paultendoLife.localChoices.at(-1);assert.equal(record.value,'farm');assert.equal(record.choice,'yes');assert.equal(record.before.legal.farm,false);assert.equal(record.after.legal.farm,true);assert.match(record.reason,/food stores are running short/);assert.equal(target.state.planet._paultendoLife.decisions.length,0);assert.equal(w.planet._paultendoLife.localChoices.length,0);check(g,warnings);
});

test('the same unrest can lead to repression or freer speech according to actual competing values',async t=>{
 for(const suppress of [false,true]){const {g,w,target,town,warnings,original}=await setup(t);town.influences.happy=-4;town.influences.crime=2;town.values={order:suppress?8:0,justice:suppress?-8:8,openness:2,change:0,wealth:0};town.legal['happy.speech']=suppress;propose(w,target,'happy.speech');assert.equal(town.legal['happy.speech'],!suppress);const record=target.state.planet._paultendoLife.localChoices.at(-1);assert.equal(record.choice,'yes');assert.equal(record.cause.allowed,!suppress);assert.equal(record.before.influences.happy,-4);assert.ok(suppress?record.after.influences.happy < -4:record.after.influences.happy > -4);assert.equal(record.cause.pressures.some(p=>p.allowed!==record.cause.allowed),suppress);visit(w,2);original.unrestBuildup.func(town);assert.ok(suppress?town.unrest>0:town.unrest===0);const panel=open(w,record);assert.match(panel.textContent,suppress?/little value|silence and obedience/:/people should be heard/);if(suppress){assert.match(panel.textContent,/The other side.*voices that challenge/s);assert.match(panel.textContent,/Spirits fall/);assert.doesNotMatch(panel.textContent,/order held|Law gains support/);}check(g,warnings);}
});

test('closed beliefs can outweigh an actual shipment need and its law physically stops that delivery',async t=>{
 const {g,w,target,town,warnings}=await setup(t);visit(w,2);town.legal.travel=true;town.values.openness=-10;const creed={id:91,name:'The Shut Door',tenets:['insular'],followers:[town.id],influences:{},extinct:false};(w.planet.religions ||= []).push(creed);town.religion=91;town.influences.faith=10;
 const center=w.chunkAt(...town.center),site=w.filterChunks(c=>!c.v.s&&c.b!=='water'&&c.v.g===center.v.g).sort((a,b)=>Math.hypot(a.x-center.x,a.y-center.y)-Math.hypot(b.x-center.x,b.y-center.y))[0];assert.ok(site);const supplier=w.happen('Create',null,null,{x:site.x,y:site.y},'town');supplier.start=1;supplier.pop=40;supplier.resources={crop:1000};supplier.jobs={};supplier._paultendoNextExchangeDay=99999;supplier.values={justice:6,openness:6};w.planet.unlocks.trade=10;town.resources.crop=10;w.gameEvents.townMarketPurchase.func(town,null,{seller:supplier,goodsType:'crop'});const exchange=w.planet._paultendoLife.exchanges.at(-1);assert.ok(exchange);visit(w,1);for(let n=0;n<12&&exchange.status==='asking';n++)advance(w,target,null);assert.equal(exchange.status,'carrying');exchange.due=99999;propose(w,target,'travel');assert.equal(town.legal.travel,false);const record=target.state.planet._paultendoLife.localChoices.at(-1);assert.ok(record.cause.pressures.some(p=>p.exchange===exchange.id&&p.allowed));assert.ok(record.cause.pressures.some(p=>p.religion===91&&!p.allowed));exchange.due=target.state.planet.day;const food=town.resources.crop;advance(w,target,null);assert.equal(town.resources.crop,food);assert.equal(exchange.resolved,false);assert.equal(exchange.status,'waiting');visit(w,2);const story=open(w,record);assert.match(story.textContent,/The other side.*shipment/s);click(w,'Follow the exchange');assert.match(story.textContent,/supplies|grain/);check(g,warnings);
});

test('open values can reopen a closed route for actual needed supplies',async t=>{
 const {g,w,target,town,warnings}=await setup(t);town.legal.travel=false;town.values.openness=8;propose(w,target,'travel');assert.equal(town.legal.travel,true);const record=target.state.planet._paultendoLife.localChoices.at(-1);assert.equal(record.cause.values.openness,8);assert.equal(record.choice,'yes');check(g,warnings);
});

test('neutral wants, missing knowledge and the recovery interval prevent automatic legal churn',async t=>{
 const {g,w,target,town,warnings}=await setup(t);advance(w,target);assert.equal(target.state.planet._paultendoLife.localChoices.length,0);town.values.openness=8;town.legal.travel=false;target.state.planet.unlocks.government=0;propose(w,target,'travel');assert.equal(town.legal.travel,false);target.state.planet.unlocks.government=10;target.state.planet.unlocks.travel=0;propose(w,target,'travel');assert.equal(town.legal.travel,false);target.state.planet.unlocks.travel=10;propose(w,target,'travel');assert.equal(town.legal.travel,true);const changed=town._paultendoLocalLawDay;town.values.openness=-10;propose(w,target,'travel');assert.equal(town.legal.travel,true);assert.equal(town._paultendoLocalLawDay,changed);for(let n=0;n<29;n++)advance(w,target,null);propose(w,target,'travel');assert.equal(town.legal.travel,false);assert.equal(target.state.planet._paultendoLife.localChoices.length,2);check(g,warnings);
});

test('enforcing a permitted crime retains its native influence effect and leaves goods and cash untouched',async t=>{
 const {g,w,target,town,warnings}=await setup(t);town.legal['crime.theft']=true;town.values.order=8;town.influences.crime=4;const stock=plain(town.resources);propose(w,target,'crime.theft');assert.equal(town.legal['crime.theft'],false);assert.ok(town.influences.crime<4);assert.deepEqual(plain(town.resources),stock);const record=target.state.planet._paultendoLife.localChoices.at(-1);assert.ok(record.after.influences.crime<record.before.influences.crime);check(g,warnings);
});

test('a construction ban pauses paid work and reopening it lets the actual project continue',async t=>{
 const {g,w,target,town,warnings}=await setup(t);visit(w,2);const p=w.happen('Create',town,null,{type:'project',subtype:'hospital',cost:40},'process');const at=w.filterChunks(c=>c.v.s===town.id&&!c.v.m)[0];p.x=at.x;p.y=at.y;town.legal['travel.construction']=false;const stock=plain(town.resources),cost=p.cost;w.metaEvents.processProject.func(p);assert.equal(p.cost,cost);assert.deepEqual(plain(town.resources),stock);assert.equal(p._paultendoBuilding.phase,'law');visit(w,1);advance(w,target);assert.equal(town.legal['travel.construction'],true);const record=target.state.planet._paultendoLife.localChoices.at(-1);assert.equal(record.cause.pressures[0].project,p.id);visit(w,2);w.metaEvents.processProject.func(p);assert.ok(p.cost<cost||p.done);assert.ok(town.resources.cash<stock.cash);assert.ok(town.resources.rock<stock.rock);assert.ok(['working','halfway','built','finished'].includes(p._paultendoBuilding.phase));assert.match(open(w,record).textContent,/Follow the building work/);check(g,warnings);
});

test('law accounts and their real effects survive reload, and reading them adds no time or choices',async t=>{
 const {g,w,target,town,warnings}=await setup(t);town.values.order=8;town.values.justice=-8;town.values.openness=2;propose(w,target,'happy.speech');const record=plain(target.state.planet._paultendoLife.localChoices.at(-1));const saved=plain(w.generateSave()),restored=await makeGame({save:saved});t.after(restored.close);const rw=restored.window;visit(rw,2);assert.deepEqual(plain(rw.planet._paultendoLife.localChoices.at(-1)),record);const rt=rw.regGet('town',town.id);assert.equal(rt.legal['happy.speech'],false);assert.equal(rt._paultendoLocalLawDay,record.day);await new Promise(resolve=>setTimeout(resolve,40));const news=rw.document.getElementById('paultendoChronicleHighlights');assert.equal(news.hidden,false);assert.equal(news.parentNode.id,'paultendoChronicleHeader');assert.match(news.textContent,/makes speech illegal/);[...news.querySelectorAll('.paultendoChronicleHeadline')].find(e=>e.textContent.includes('makes speech illegal')).querySelector('.paultendoChronicleRead').click();assert.match(rw.document.getElementById('actionSubList').textContent,/Spirits fall/);const before=plain({day:rw.planet.day,life:rw.planet._paultendoLife,resources:rt.resources,legal:rt.legal,influences:rt.influences,fog:rw.planet._paultendoFog});let draws=0;const random=rw.Math.random;rw.Math.random=()=>{draws++;return random();};const story=open(rw,record);assert.match(story.textContent,/Spirits fall.*Speech is still forbidden/s);assert.equal(draws,0);assert.deepEqual(plain({day:rw.planet.day,life:rw.planet._paultendoLife,resources:rt.resources,legal:rt.legal,influences:rt.influences,fog:rw.planet._paultendoFog}),before);rw.Math.random=random;assert.deepEqual(restored.errors,[]);check(g,warnings);
});

test('unobserved towns decide without exposing identities or displacing a live visited-world choice',async t=>{
 const {g,w,home,target,town,warnings}=await setup(t);town._hidden=true;town.values.order=8;town.values.justice=-8;const events=w.currentEvents,settings=w.userSettings,active=w.planet;const base=w.chooseEvent;let pending;w.chooseEvent=()=>{if(w.planet===target.state.planet)return 'townLaw';pending={eventClass:'townLaw',needsInput:true,done:false,subject:w.currentPlayer,target:home,args:{value:'happy.speech',result:false,influence:'happy',name:'speech'}};w.currentEvents.liveLaw=pending;return null;};try{w.nextDay();}finally{w.chooseEvent=base;}assert.equal(town.legal['happy.speech'],false);assert.equal(w.planet,active);assert.equal(w.userSettings,settings);assert.equal(w.currentEvents,events);assert.equal(w.currentEvents.liveLaw,pending);assert.equal(pending.done,false);assert.equal(home.legal['happy.speech'],undefined);assert.doesNotMatch(w.document.getElementById('logMessages').textContent,/Farbank/);assert.doesNotMatch(decodeURIComponent(target.state.planet._paultendoLogHTML.slice(4)),/Farbank|localChoice/);assert.equal(target.state.planet._paultendoLife.localChoices.length,1);check(g,warnings);
});
