import test from 'node:test';
import assert from 'node:assert/strict';
import {makeGame,settleGame} from './harness.mjs';
const plain=x=>JSON.parse(JSON.stringify(x));
const life=w=>w.planet._paultendoLife;
function quiet(w){for(const event of Object.values(w.dailyEvents)){if(event.func)event.func=()=>{};if(event.perChunk)event.perChunk=()=>{};}}
function next(w,n=1){const choose=w.chooseEvent;w.chooseEvent=()=>null;try{for(let i=0;i<n;i++)w.nextDay();}finally{w.chooseEvent=choose;}}
function click(w,text){const p=w.document.getElementById('actionSubList'),b=[...p.querySelectorAll('[role="button"]')].find(b=>b.textContent.includes(text));assert.ok(b,`${text}: ${p.textContent}`);b.click();}
function visit(w,id){w.document.getElementById('actionItem-solar').click();w.document.querySelector(`[data-world-id="${id}"]`).click();click(w,'Switch to world');}
function meet(w,town){w.openRegBrowser(town,'town');[...w.document.querySelectorAll('.paultendoTownLife button')].find(b=>b.textContent==='Meet the people').click();for(const p of town._paultendoPeople)p.outlook='curious';}
function configure(w,town,food){Object.assign(town,{name:food?'Homebank':'Farbank',start:1,pop:100,jobs:{miner:30,farmer:40,scholar:5},resources:{crop:food,metal_tools:50,cargo_vessel:food?1:0,charcoal:food?20:0},values:{justice:6,openness:4},research:{farm:10},wealth:60,_paultendoNextExchangeDay:99999});town.influences.trade=0;Object.assign(w.planet.unlocks,{education:70,smith:70,fire:70,travel:90,astronomy:20,trade:30,farm:10});meet(w,town);const at=w.chunkAt(...town.center);at.b='badlands';at.e=1;return at;}
async function setup(t,{learn=true}={}){const g=await makeGame();t.after(g.close);const w=g.window,warnings=[];w.console.warn=(...a)=>warnings.push(a.map(String).join(' '));const mine=w.gameEvents.townMine.perChunk,home=settleGame(g);w.planet.day=80;configure(w,home,1000);quiet(w);let work;
 if(learn){home.research={smith:100};w.happen('AddResource',null,home,{type:'glass',count:1});w.happen('AddResource',null,home,{type:'steel',count:2});const caller=w.readyEvent('unlockPrecisionEngineering');assert.ok(caller);caller.args.value={town:home.id};w.doEvent('unlockPrecisionEngineering',caller);work=life(w).inquiries.at(-1);for(let i=0;i<24&&work.status!=='learned';i++)next(w);assert.equal(work.status,'learned');home.research={farm:10};}
 else w.planet.unlocks.smith=80;
 const target=w._paultendoUniverse.worlds[2];target.discovered=true;target.reached=true;visit(w,2);const at=w.filterChunks(c=>!c.v.s&&c.b!=='water'&&c.b!=='mountain')[0],away=w.happen('Create',null,null,{x:at.x,y:at.y},'town'),rock=configure(w,away,0);w.planet.unlocks.astronomy=0;w.happen('Explore',null,null,{x:rock.x,y:rock.y});quiet(w);visit(w,1);w._paultendoUniverse._paultendoColonization.history.push({id:900,stage:'completed',originWorldId:1,originTownId:home.id,colony:{worldId:2,townId:away.id}});return {g,w,home,away,target,rock,mine,work,warnings};}
function launch(w){next(w);const route=w._paultendoUniverse.spaceRoutes[0];assert.ok(route);next(w);assert.equal(route.status,'outbound');return route;}
function arrive(w,route){const due=route.journey.arrival;while(w.planet.day<due)next(w);assert.equal(route.deliveries,1);}
function markReady(w,target){for(let i=0;i<12&&!target.state.planet._paultendoLife.surfaceMarks.some(m=>m.status==='made');i++)next(w);const mark=target.state.planet._paultendoLife.surfaceMarks.find(m=>m.status==='made');assert.ok(mark,JSON.stringify(target.state.planet._paultendoLife.surfaceMarks));return mark;}
function read(w,away,rock,mine){for(let i=0;i<30&&!life(w).clues.length;i++)mine(away,null,rock);assert.equal(life(w).clues.length,1,JSON.stringify({marks:life(w).surfaceMarks,people:away._paultendoPeople,work:life(w).materialWork,resources:away.resources,rock:{x:rock.x,y:rock.y},world:w.planet._paultendoWorldId}));return life(w).clues[0];}
function check(g,warnings){assert.deepEqual(g.errors,[]);assert.deepEqual(warnings,[]);}

test('a cargo visit carries a real maker’s account, and local carving spends a local tool before anyone can find it',async t=>{
 const {g,w,home,away,target,work,warnings}=await setup(t),route=launch(w),trip=route.journey;assert.equal(trip.sketch.source,work.id);assert.equal(trip.sketch.world,1);assert.equal(away.id,home.id);assert.equal(away._paultendoVisitorSketches,undefined);arrive(w,route);assert.equal(away._paultendoVisitorSketches.length,1);assert.equal(away._paultendoLocalDiscoveries,undefined);const mark=markReady(w,target);assert.equal(mark.source.via.journey,trip.id);assert.equal(mark.source.world,1);assert.equal(mark.town,away.id);assert.equal(mark.name,away._paultendoPeople.find(p=>p.id===mark.person).name);assert.equal(away._paultendoCarvingTools[0].type,'metal_tools');assert.equal(away._paultendoCarvingTools[0].uses,79);assert.equal(away.resources.metal_tools,49);assert.equal(target.state.planet._paultendoLife.clues.length,0);check(g,warnings);
});

test('reading remembers a clue through reload and waits for prerequisites and a real local need, then pays for trials',async t=>{
 const {g,w,away,target,rock,mine,work,warnings}=await setup(t),route=launch(w);arrive(w,route);const mark=markReady(w,target);visit(w,2);w.planet.unlocks.smith=60;const clue=read(w,away,rock,mine);assert.equal(clue.inquiry,undefined);next(w,3);assert.equal(clue.status,'unfamiliar');assert.equal(away._paultendoLocalDiscoveries,undefined);const saved=plain(w.generateSave()),restored=await makeGame({save:saved});t.after(restored.close);const rw=restored.window;quiet(rw);const rt=rw.regGet('town',away.id),copy=life(rw).clues[0];assert.equal(copy.mark,mark.id);rw.planet.unlocks.smith=70;next(rw,3);assert.equal(copy.status,'remembered');assert.equal(copy.inquiry,undefined);
 rt.research={smith:100};rw.happen('AddResource',null,rt,{type:'glass',count:1});rw.happen('AddResource',null,rt,{type:'steel',count:2});next(rw,3);assert.equal(copy.status,'studying',JSON.stringify(copy));const local=life(rw).inquiries.find(x=>x.id===copy.inquiry);assert.equal(local.guidance.world,1);assert.equal(local.guidance.source,work.id);assert.equal(local.guidance.mark,mark.id);assert.equal(local.days,16);assert.equal(local.status,'working');assert.equal(rt.resources.glass || 0,0);assert.equal(rt.resources.steel || 0,0);assert.equal(rt._paultendoLocalDiscoveries,undefined);
 for(let i=0;i<24&&local.status!=='learned';i++)next(rw);assert.equal(local.status,'learned');assert.equal(rt._paultendoLocalDiscoveries['smith:80'].guidance.mark,mark.id);assert.equal(life(rw).inquiries.filter(x=>x.event===local.event&&x.town===rt.id).length,1);check(g,warnings);assert.deepEqual(restored.errors,[]);
});

test('a milestone without an actual teacher cannot seed a diagram, and a guarded maker keeps their account home',async t=>{
 for(const legacy of [true,false]){const {g,w,home,away,work,warnings}=await setup(t,{learn:!legacy});if(work)home._paultendoPeople.find(p=>p.id===work.person).outlook='guarded';const route=launch(w);assert.equal(route.journey.sketch,undefined);arrive(w,route);assert.equal(away._paultendoVisitorSketches,undefined);check(g,warnings);}
});

test('a failed landing teaches nothing and a saved shipment cannot duplicate the clue or its provenance',async t=>{
 const {g,w,away,target,warnings}=await setup(t),route=launch(w),trip=route.journey;away.resources.crop=1000000000;while(w.planet.day<trip.arrival)next(w);assert.equal(route.pause,'room');assert.equal(away._paultendoVisitorSketches,undefined);const restored=await makeGame({save:plain(w.generateSave())});t.after(restored.close);const rw=restored.window;quiet(rw);const rr=rw._paultendoUniverse.spaceRoutes[0],world=rw._paultendoUniverse.worlds[2],rt=world.state.planet.reg.town[away.id];rt.resources.crop=0;next(rw);assert.equal(rt._paultendoVisitorSketches.length,1);assert.equal(rt._paultendoVisitorSketches[0].via.journey,trip.id);next(rw,4);assert.equal(rt._paultendoVisitorSketches.length,1);check(g,warnings);assert.deepEqual(restored.errors,[]);assert.equal(target.state.planet._paultendoLife.surfaceMarks.length,0);
});

test('intrigue starts real attention before technical prerequisites and the reader’s idea can spread without awarding the discovery',async t=>{
 const {g,w,away,target,rock,mine,warnings}=await setup(t),route=launch(w);arrive(w,route);const mark=markReady(w,target);visit(w,2);w.planet.unlocks.smith=20;const clue=read(w,away,rock,mine);next(w,2);assert.equal(clue.study.status,'working');assert.equal(clue.study.person,clue.person);assert.equal(clue.status,'unfamiliar');assert.equal(clue.inquiry,undefined);assert.equal(away._paultendoLocalDiscoveries,undefined);const remaining=clue.study.remaining;away.resources.crop=0;next(w,2);assert.equal(clue.study.pause,'food');assert.equal(clue.study.remaining,remaining);away.resources.crop=1000;next(w,3);assert.equal(clue.study.status,'finished');assert.equal(clue.study.interpretation.meaning,'pattern');assert.equal(clue.study.interpretation.prepared,false);const teaching=life(w).teachings.find(t=>t.id===clue.study.teaching);assert.ok(teaching);assert.equal(teaching.origin.cause.mark,mark.id);assert.equal(teaching.words,'Try to understand the things no one can explain.');assert.equal(away._paultendoLocalDiscoveries,undefined);const before=plain({clue,mark,teachings:life(w).teachings,day:w.planet.day});const entry=w.document.querySelector(`[data-story-kind="inscription"][data-story-id="${mark.id}"]`);entry.querySelector('.paultendoChronicleStoryLink').click();assert.match(w.document.getElementById('actionSubList').textContent,/cannot say what they were meant for/);assert.deepEqual(plain({clue,mark,teachings:life(w).teachings,day:w.planet.day}),before);check(g,warnings);
});

test('a priest can read a message into an unfamiliar pattern and keep that interpretation through reload',async t=>{
 const {g,w,away,target,rock,mine,warnings}=await setup(t),route=launch(w);arrive(w,route);const mark=markReady(w,target);visit(w,2);w.planet.unlocks.smith=20;away.jobs.priest=2;away.influences.faith=6;meet(w,away);const priest=away._paultendoPeople.find(p=>p.role==='priest');priest.outlook='steadfast';const clue=read(w,away,rock,mine);clue.person=priest.id;clue.name=priest.name;next(w,6);assert.equal(clue.study.interpretation.meaning,'belief');assert.equal(clue.study.interpretation.prepared,false);const teaching=life(w).teachings.find(t=>t.id===clue.study.teaching);assert.equal(teaching.meaning,'belief');assert.equal(teaching.words,'Someone left these signs for us.');assert.equal(away._paultendoLocalDiscoveries,undefined);const restored=await makeGame({save:plain(w.generateSave())});t.after(restored.close);assert.deepEqual(plain(life(restored.window).clues.find(c=>c.id===clue.id).study.interpretation),plain(clue.study.interpretation));assert.equal(mark.source.event,'unlockPrecisionEngineering');check(g,warnings);assert.deepEqual(restored.errors,[]);
});

test('an intrigued copier can preserve an advanced diagram without understanding it, and altered details provide less help later',async t=>{
 const {g,w,away,target,rock,mine,warnings}=await setup(t),route=launch(w);target.state.planet.unlocks.smith=60;arrive(w,route);const mark=markReady(w,target);assert.equal(mark.fidelity,.5);assert.equal(away._paultendoLocalDiscoveries,undefined);assert.equal(mark.source.event,'unlockPrecisionEngineering');visit(w,2);w.openRegBrowser(away,'town');[...w.document.querySelectorAll('.paultendoTownLife button')].find(b=>b.textContent==='Marks left here').click();click(w,'A diagram');assert.match(w.document.getElementById('actionSubList').textContent,/copied unfamiliar lines/);const clue=read(w,away,rock,mine);w.planet.unlocks.smith=70;away.research={smith:100};w.happen('AddResource',null,away,{type:'glass',count:1});w.happen('AddResource',null,away,{type:'steel',count:2});for(let i=0;i<12&&!clue.inquiry;i++)next(w);const inquiry=life(w).inquiries.find(x=>x.id===clue.inquiry);assert.ok(inquiry);assert.equal(inquiry.guidance.helpDays,1);assert.equal(inquiry.days,17);check(g,warnings);
});
