import test from 'node:test';
import assert from 'node:assert/strict';
import {makeGame,settleGame} from './harness.mjs';
const life=w=>w.planet._paultendoLife;
const plain=x=>JSON.parse(JSON.stringify(x));
const panel=w=>w.document.getElementById('actionSubList');
function click(w,text){const button=[...panel(w).querySelectorAll('[role="button"]')].find(e=>e.textContent.includes(text));assert.ok(button,`${text}: ${panel(w).textContent}`);button.click();}
// War consequences have separate scenarios. These orders keep a peaceful route.
function controlled(w){for(const id of ['warPressureDynamics','townFarm','townTame','townMine','townLumber','townBirth','townDeath','townExpand','townEconomyTick','townTax'])if(w.gameEvents[id]){if(w.gameEvents[id].func)w.gameEvents[id].func=()=>{};if(w.gameEvents[id].perChunk)w.gameEvents[id].perChunk=()=>{};}w.gameEvents.processAll.func=()=>{};}
function next(w){const choose=w.chooseEvent;w.chooseEvent=()=>null;try{w.nextDay();}finally{w.chooseEvent=choose;}}
function add(w,town,type,count){w.happen('AddResource',null,town,{type,count});}
function people(w,town){w.openRegBrowser(town,'town');[...w.document.querySelectorAll('.paultendoTownLife button')].find(e=>e.textContent==='Meet the people').click();for(const p of town._paultendoPeople){p.outlook='curious';p.trust=90;}}
function pair(g){const w=g.window,seller=settleGame(g);w.planet.day=10;const center=w.planet.chunks[seller.center.join(',')],chunk=w.filterChunks(c=>!c.v.s&&c.v.g===center.v.g&&c.b!=='water'&&c.b!=='mountain').sort((a,b)=>Math.hypot(a.x-center.x,a.y-center.y)-Math.hypot(b.x-center.x,b.y-center.y))[0];const buyer=w.happen('Create',null,null,{x:chunk.x,y:chunk.y},'town');for(const [town,name] of [[seller,'Ashbank'],[buyer,'Wick']]){town.name=name;town.pop=20;town.resources={crop:2000,cash:0};town.jobs={};town.values={justice:6,openness:6};town.research={farm:100};town.legal.farm=false;town.guidanceTrust=90;town._paultendoNextExchangeDay=9999;}seller.jobs={miner:20};buyer.jobs={doctor:20};Object.assign(w.planet.unlocks,{fire:50,smith:50,education:20,trade:30});controlled(w);people(w,seller);people(w,buyer);return {w,seller,buyer};}
function lens(w,buyer){buyer.resources.metal=2;people(w,buyer);click(w,'Doctor');click(w,'Make something of your own');click(w,'Make a clear lens');const voice=life(w).whispers.at(-1);voice.roll=0;w.planet.day=voice.due-1;next(w);return life(w).artifactWork.at(-1);}
function masterGlass(w,seller){add(w,seller,'sand',3);add(w,seller,'charcoal',2);seller.resources.rock=1;next(w);const first=life(w).materialWork.find(x=>x.town===seller.id&&x.type==='glass');assert.ok(first);first.roll=.99;for(let n=0;n<20&&first.status!=='made';n++)next(w);assert.equal(first.status,'made');w.happen('RemoveResource',null,seller,{type:'glass',count:2});w.planet.day+=8;add(w,seller,'sand',3);add(w,seller,'charcoal',2);seller.resources.rock=1;return first;}
function ask(w,buyer,seller){w.gameEvents.townMarketPurchase.func(buyer,null,{seller,goodsType:'glass'});const request=life(w).exchanges.find(r=>r.buyer===buyer.id&&!r.resolved);assert.ok(request);w.planet.day=request.due-1;next(w);return request;}
function finish(w,request){for(let n=0;n<35&&!request.resolved;n++)next(w);assert.equal(request.status,'arrived',JSON.stringify(request));}
function errors(g){assert.deepEqual(g.errors,[]);}

test('a neighbour’s actual lens need commissions glass from an idle practiced workshop without a supplier whisper',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);masterGlass(w,seller);const craft=lens(w,buyer);assert.equal(craft.status,'gathering');buyer._paultendoNextExchangeDay=0;next(w);const request=life(w).exchanges.find(r=>r.buyer===buyer.id&&!r.resolved);assert.ok(request);w.planet.day=request.due-1;next(w);assert.equal(request.status,'making');const batch=life(w).materialWork.find(x=>x.id===request.manufacture.work);assert.equal(batch.purpose.exchange,request.id);assert.equal(batch.trial,false);assert.equal(batch.status,'working');assert.equal(seller.resources.sand || 0,0);assert.equal(seller.resources.charcoal || 0,0);assert.equal(seller.resources.rock || 0,0);assert.equal(buyer.resources.glass,undefined);assert.equal(request.cargo,0);assert.equal(life(w).whispers.length,1);
 finish(w,request);assert.equal(request.kind,'aid');assert.equal(request.delivered,1);assert.equal(seller.resources.glass,1);assert.equal(buyer._paultendoMaterials.glass.technique,undefined);for(let n=0;n<20&&craft.status!=='made';n++)next(w);assert.equal(craft.status,'made');const object=life(w).artifacts.find(x=>x.id===craft.artifact);assert.equal(object.origin.materialProductions[0].work,batch.id);assert.equal(request.uses.find(u=>u.kind==='craft').count,1);assert.equal(life(w).materialWork.filter(x=>x.town===seller.id&&x.type==='glass').length,2,'Satisfied demand must not start endless export batches');
 const log=[...w.document.querySelectorAll('.logMessage')].find(e=>e.dataset.storyId===request.id);log.querySelector('.paultendoChronicleStoryLink').click();assert.match(panel(w).textContent,/agrees to make 1 glass/);click(w,'Visit the workshop');assert.match(panel(w).textContent,/request for glass/);assert.match(panel(w).textContent,/Used 3 sand, 2 charcoal,? and 1 stone/);errors(g);
});

test('global technique and a received sample do not pretend a town knows how to manufacture for others',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);add(w,seller,'glass',1);w.happen('RemoveResource',null,seller,{type:'glass',count:1});lens(w,buyer);Object.assign(seller.resources,{sand:3,charcoal:2,rock:1});assert.equal(life(w).materialWork.filter(x=>['waiting','working'].includes(x.status)).length,0);w.gameEvents.townMarketPurchase.func(buyer,null,{seller,goodsType:'glass'});assert.equal(life(w).exchanges.length,0);assert.equal(seller._paultendoMaterials.glass.technique,undefined);errors(g);
});

test('paid workshop requests keep their agreed price and exchange actual cash only when finished goods depart',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);masterGlass(w,seller);seller.values={justice:-6,openness:0};for(const p of seller._paultendoPeople)p.outlook='guarded';buyer.resources.cash=500;lens(w,buyer);const request=ask(w,buyer,seller);assert.equal(request.status,'making');const terms=plain(request.manufacture.terms);assert.equal(terms.kind,'trade');assert.equal(buyer.resources.cash,500);assert.equal(request.paymentCargo,undefined);assert.equal(seller.resources.cash,0);finish(w,request);assert.equal(request.payment.count,terms.payment.count);assert.equal(buyer.resources.cash+seller.resources.cash,500);assert.equal(seller.resources.cash,request.paid);assert.equal(request.materialLesson.withheld,true);errors(g);
});

test('an insular unpaid workshop may refuse real work rather than help every neighbour',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);masterGlass(w,seller);seller.values={justice:-6,openness:-6};for(const p of seller._paultendoPeople)p.outlook='guarded';lens(w,buyer);const count=life(w).materialWork.length,request=ask(w,buyer,seller);assert.equal(request.status,'refused');assert.equal(request.refusal,'outsiders');assert.equal(life(w).materialWork.length,count);assert.equal(seller.resources.sand,3);assert.equal(request.manufacture,undefined);errors(g);
});

test('supplies already promised to local construction cannot finance a neighbour’s firing',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);masterGlass(w,seller);lens(w,buyer);w.happen('Create',seller,null,{type:'project',subtype:'school',cost:20},'process');w.gameEvents.townMarketPurchase.func(buyer,null,{seller,goodsType:'glass'});assert.equal(life(w).exchanges.length,0);assert.equal(seller.resources.rock,1);errors(g);
});

test('withdrawn demand leaves already paid work to finish into the maker’s stores',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);masterGlass(w,seller);const craft=lens(w,buyer);const request=ask(w,buyer,seller),batch=life(w).materialWork.find(x=>x.id===request.manufacture.work);assert.equal(batch.status,'working');craft.status='abandoned';next(w);assert.equal(request.status,'withdrawn');assert.equal(request.paymentCargo,undefined);for(let n=0;n<10&&batch.status!=='made';n++)next(w);assert.equal(batch.status,'made');assert.equal(seller.resources.glass,2);assert.equal(buyer.resources.glass,undefined);errors(g);
});

test('a road closed during production holds goods and their reservation through reload until actual travel resumes',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);masterGlass(w,seller);lens(w,buyer);const request=ask(w,buyer,seller);w.planet.embargoes.push({fromId:buyer.id,toId:seller.id});for(let n=0;n<9;n++)next(w);assert.equal(request.status,'making');assert.equal(request.cargo,0);assert.equal(seller.resources.glass,2);assert.equal(request.steps.filter(x=>x.kind==='workBlocked').length,1);
 const restored=await makeGame({save:plain(w.generateSave())});t.after(restored.close);const rw=restored.window;controlled(rw);const copy=life(rw).exchanges.find(x=>x.id===request.id);assert.deepEqual(plain(copy.manufacture),plain(request.manufacture));rw.planet.embargoes=[];finish(rw,copy);assert.equal(copy.delivered,1);assert.equal(rw.regGet('town',seller.id).resources.glass,1);assert.ok(rw.regGet('town',buyer.id)._paultendoCommodityLots.glass.some(l=>l.production.work===copy.manufacture.work));errors(g);errors(restored);
});

test('missing inputs, workers, food or free workshop capacity prevent impossible production offers',async t=>{
 for(const shortage of ['inputs','workers','food','capacity']){const g=await makeGame();try{const {w,seller,buyer}=pair(g);masterGlass(w,seller);lens(w,buyer);if(shortage==='inputs')seller.resources.sand=0;if(shortage==='workers')seller.jobs.miner=0;if(shortage==='food')seller.resources.crop=0;if(shortage==='capacity')life(w).materialWork.push({id:'busy',town:seller.id,type:'glass',status:'working',remaining:99,person:seller._paultendoPeople[0].id,cost:{},output:2,steps:[],trial:false,started:w.planet.day});w.gameEvents.townMarketPurchase.func(buyer,null,{seller,goodsType:'glass'});assert.equal(life(w).exchanges.length,0,shortage);errors(g);}finally{g.close();}}
});

test('a request withdrawn before reaching the workshop neither starts production nor charges the buyer',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);masterGlass(w,seller);const craft=lens(w,buyer),count=life(w).materialWork.length;w.gameEvents.townMarketPurchase.func(buyer,null,{seller,goodsType:'glass'});const request=life(w).exchanges.at(-1);assert.equal(request.status,'asking');craft.status='abandoned';w.planet.day=request.due-1;next(w);assert.equal(request.status,'withdrawn');assert.equal(request.manufacture,undefined);assert.equal(life(w).materialWork.length,count);assert.equal(seller.resources.sand,3);assert.equal(seller.resources.charcoal,2);assert.equal(seller.resources.rock,1);errors(g);
});

test('steel manufacture answers an actual instrument request through the same workshop and exchange model',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);seller.research={education:100};seller.resources.metal=2;add(w,seller,'coal',1);next(w);const first=life(w).materialWork.find(x=>x.town===seller.id&&x.type==='steel');assert.ok(first);first.roll=.99;for(let n=0;n<20&&first.status!=='made';n++)next(w);assert.equal(first.status,'made');seller.research={farm:100};w.happen('RemoveResource',null,seller,{type:'steel',count:2});w.planet.day+=8;seller.resources.metal=2;add(w,seller,'coal',1);buyer.jobs={musician:20};add(w,buyer,'steel',1);people(w,buyer);click(w,'Musician');click(w,'Make something of your own');click(w,'Make a tuning fork from steel');const voice=life(w).whispers.at(-1);voice.roll=0;w.planet.day=voice.due-1;next(w);const craft=life(w).artifactWork.at(-1);assert.equal(craft.status,'gathering');w.gameEvents.townMarketPurchase.func(buyer,null,{seller,goodsType:'steel'});const request=life(w).exchanges.at(-1);w.planet.day=request.due-1;next(w);assert.equal(request.status,'making');const batch=life(w).materialWork.find(x=>x.id===request.manufacture.work);assert.deepEqual(plain(batch.cost),{metal:2,coal:1});finish(w,request);assert.equal(request.delivered,2);assert.equal(seller.resources.metal || 0,0);assert.equal(seller.resources.coal || 0,0);for(let n=0;n<20&&craft.status!=='made';n++)next(w);assert.equal(craft.status,'made');const object=life(w).artifacts.find(x=>x.id===craft.artifact);assert.equal(object.quality,.8);assert.equal(object.origin.materialProductions[0].work,batch.id);assert.equal(buyer._paultendoMaterials.steel.technique,undefined);errors(g);
});

test('finished bricks promised to a neighbour cannot be consumed by a new native building project',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);seller.resources.clay=2;add(w,seller,'charcoal',1);const school=w.happen('Create',seller,null,{type:'project',subtype:'school',cost:20},'process');next(w);const first=life(w).materialWork.find(x=>x.town===seller.id&&x.type==='brick');assert.ok(first);first.roll=.99;for(let n=0;n<20&&first.status!=='made';n++)next(w);assert.equal(first.status,'made');school.done=true;school.cost=0;w.happen('RemoveResource',null,seller,{type:'brick',count:2});w.planet.day+=8;seller.resources.clay=2;add(w,seller,'charcoal',1);add(w,buyer,'brick',1);w.happen('RemoveResource',null,buyer,{type:'brick',count:1});const home=w.happen('Create',buyer,null,{type:'project',subtype:'school',cost:20},'process');w.gameEvents.townMarketPurchase.func(buyer,null,{seller,goodsType:'brick'});const request=life(w).exchanges.at(-1);w.planet.day=request.due-1;next(w);assert.equal(request.status,'making');w.planet.embargoes.push({fromId:buyer.id,toId:seller.id});for(let n=0;n<6;n++)next(w);assert.equal(seller.resources.brick,2);const local=w.happen('Create',seller,null,{type:'project',subtype:'school',cost:20},'process');const random=w.Math.random;w.Math.random=()=>0;try{w.metaEvents.processProject.func(local);}finally{w.Math.random=random;}assert.equal(seller.resources.brick,2,'The existing order holds its finished goods');assert.equal(local.cost,20);w.planet.embargoes=[];next(w);assert.equal(request.status,'making','A new local shortage can hold the order');assert.equal(request.steps.at(-1).kind,'workStores');seller.resources.rock=10;finish(w,request);assert.equal(request.delivered,2);assert.equal(seller.resources.brick || 0,0);assert.equal(home.cost,20);errors(g);
});

test('losing the ability to pay cancels delivery without creating money or destroying the finished material',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);masterGlass(w,seller);seller.values={justice:-6,openness:0};for(const p of seller._paultendoPeople)p.outlook='guarded';buyer.resources.cash=500;lens(w,buyer);const request=ask(w,buyer,seller);assert.equal(request.status,'making');buyer.resources.cash=0;for(let n=0;n<12&&!request.resolved;n++)next(w);assert.equal(request.status,'refused');assert.equal(seller.resources.glass,2);assert.equal(seller.resources.cash,0);assert.equal(request.paymentCargo,undefined);assert.equal(request.cargo,0);assert.equal(buyer.resources.glass,undefined);errors(g);
});

test('a hungry workshop pauses real ordered work and resumes without paying its inputs twice',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);masterGlass(w,seller);lens(w,buyer);const request=ask(w,buyer,seller),batch=life(w).materialWork.find(x=>x.id===request.manufacture.work),remaining=batch.remaining;seller.resources.crop=0;buyer.resources.crop=0;for(let n=0;n<3;n++)next(w);assert.equal(batch.remaining,remaining);assert.match(batch.pause,/food/);assert.equal(request.cargo,0);seller.resources.crop=1000;buyer.resources.crop=1000;finish(w,request);assert.equal(batch.status,'made');assert.equal(seller.resources.sand || 0,0);assert.equal(seller.resources.charcoal || 0,0);assert.equal(request.delivered,1);errors(g);
});

test('an unseen supplier can fill an actual order without exposing the worker or settlement in the visible account',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);masterGlass(w,seller);seller._hidden=true;lens(w,buyer);const request=ask(w,buyer,seller);assert.equal(request.status,'making');const maker=request.manufacture.name;const commission=[...w.document.querySelectorAll('.logMessage')].find(e=>e.dataset.storyId===request.id&&e.textContent.includes('agrees to make'));assert.ok(commission);assert.doesNotMatch(commission.textContent,new RegExp(`${seller.name}|${maker}`));assert.match(commission.textContent,/A maker in another settlement/);finish(w,request);assert.equal(request.delivered,1);assert.equal(request.known[seller.id],undefined);errors(g);
});

test('completed work serving a blocked order survives history trimming and remains deliverable',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);masterGlass(w,seller);lens(w,buyer);const request=ask(w,buyer,seller);w.planet.embargoes.push({fromId:buyer.id,toId:seller.id});for(let n=0;n<9;n++)next(w);const batch=life(w).materialWork.find(x=>x.id===request.manufacture.work);assert.equal(batch.status,'made');for(let n=0;n<140;n++)life(w).materialWork.push({id:`past:${n}`,town:seller.id,type:'glass',status:'made',day:1,finished:2,steps:[]});next(w);assert.ok(life(w).materialWork.includes(batch));assert.equal(request.status,'making');w.planet.embargoes=[];finish(w,request);assert.equal(request.delivered,1);errors(g);
});

test('a neighbour’s food gift can revive its supplier’s workshop and let the requested glass arrive',async t=>{
 const g=await makeGame();t.after(g.close);const {w,seller,buyer}=pair(g);masterGlass(w,seller);lens(w,buyer);const request=ask(w,buyer,seller),batch=life(w).materialWork.find(x=>x.id===request.manufacture.work);seller.resources.crop=0;next(w);assert.match(batch.pause,/food/);finish(w,request);const relief=life(w).exchanges.find(r=>r.buyer===seller.id&&r.seller===buyer.id&&r.type==='crop');assert.ok(relief);assert.equal(relief.kind,'aid');assert.equal(relief.status,'arrived');assert.ok(relief.uses.some(u=>u.kind==='meals'&&u.count>0));assert.equal(batch.status,'made');assert.ok(batch.finished>=relief.arrived);assert.ok(batch.steps.some(s=>s.text.includes('not enough food')));assert.ok(batch.steps.some(s=>s.text.includes('Food from Wick')));assert.equal(batch.relief[0].exchange,relief.id);assert.equal(request.delivered,1);assert.ok(request.arrived>=batch.finished);assert.equal(life(w).whispers.length,1);const log=[...w.document.querySelectorAll('.logMessage')].find(e=>e.dataset.storyId===batch.id);log.querySelector('.paultendoChronicleStoryLink').click();click(w,'Remember the food that reached them');assert.match(panel(w).textContent,/grains? from this exchange feeds people|Grain from this exchange feeds people/i);errors(g);
});
