// Mechanical build of exported artwork into indexed 32x32 sprites and the
// single-file mod. ImageMagick is a development tool, never a game dependency.
import { readFileSync, writeFileSync, renameSync } from 'node:fs';
import { resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const manifestPath = resolve(root, 'artwork/paultendo-sprites/manifest.json');
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
const base = resolve(root, 'artwork/paultendo-sprites');
const data = { version: 1, sprites: {}, overlays: {} };
const magick = process.env.SPRITE_MAGICK || 'magick';
// Readers, including running games and tests, must never see a partial script.
const writeComplete = (path, contents) => {
    const temporary = path + '.sprite-build-' + process.pid;
    writeFileSync(temporary, contents);
    renameSync(temporary, path);
};
for (const asset of manifest.assets) {
    const input = resolve(base,asset.file);
    const rgba = execFileSync(magick,[input,'-depth','8','rgba:-']);
    if (rgba.length !== 32*32*4) throw new Error(asset.id+' is not 32x32');
    const counts = new Map();
    for(let i=0;i<rgba.length;i+=4) if(rgba[i+3]>=128) {
        const colour='#'+rgba.subarray(i,i+3).toString('hex');
        counts.set(colour,(counts.get(colour)||0)+1);
    }
    const entries=[...counts.keys()].sort((a,b)=>{
        const light=c=>parseInt(c.slice(1,3),16)*0.2126+parseInt(c.slice(3,5),16)*0.7152+parseInt(c.slice(5,7),16)*0.0722;
        return light(a)-light(b);
    });
    if(entries.length>15)throw new Error(asset.id+' exceeds 15 visible colours');
    const palette=[{colour:null,role:'transparent'},...entries.map((colour,index)=>({colour,role:index===0?'outline':asset.roles?.[colour]?.role || 'body',shade:asset.roles?.[colour]?.shade ?? Math.min(3,Math.floor(index*4/entries.length))}))];
    const indices=new Map(entries.map((colour,index)=>[colour,(index+1).toString(16)]));
    let pixels='';
    for(let i=0;i<rgba.length;i+=4) pixels+=rgba[i+3]>=128?indices.get('#'+rgba.subarray(i,i+3).toString('hex')):'0';
    const regionCodes={transparent:'.',outline:'o',body:'b',accent:'a',fixed:'f',surface:'s'};
    const regions=[...pixels].map(code=>regionCodes[palette[parseInt(code,16)].role]);
    for(const rect of asset.regions || [])for(let y=rect.y;y<rect.y+rect.height;y++)for(let x=rect.x;x<rect.x+rect.width;x++) {
        const i=y*32+x;
        if(x>=0&&x<32&&y>=0&&y<32&&['b','s'].includes(regions[i]))regions[i]=regionCodes[rect.role];
    }
    const sprite={palette,rows:Array.from({length:32},(_,y)=>pixels.slice(y*32,y*32+32)),regions:Array.from({length:32},(_,y)=>regions.slice(y*32,y*32+32).join(''))};
    if(asset.overlayOffsets){
        for(const [name,offset] of Object.entries(asset.overlayOffsets))if(!['worn','cracked','repaired'].includes(name)||!['x','y'].every(axis=>Number.isInteger(offset[axis])&&Math.abs(offset[axis])<32))throw new Error(asset.id+' has an invalid overlay position');
        sprite.overlayOffsets=asset.overlayOffsets;
    }
    if(asset.id.startsWith('overlay-'))data.overlays[asset.id.slice(8)]=sprite;
    else data.sprites[asset.id]=sprite;
    asset.sha256=createHash('sha256').update(readFileSync(input)).digest('hex');
    asset.sourceSha256=createHash('sha256').update(readFileSync(resolve(base,asset.source))).digest('hex');
    asset.colours=entries.length+1;asset.bytes=readFileSync(input).length;
}
const factory=readFileSync(resolve(root,'app/sprites/renderer.js'),'utf8');
const encoded=JSON.stringify(data);
const sprites=manifest.assets.filter(asset=>!asset.id.startsWith('overlay-'));
const atlas=resolve(root,'app/sprites/atlas.png');
execFileSync(magick,[...sprites.map(asset=>resolve(base,asset.file)),'+append','-strip',atlas]);
sprites.forEach((asset,index)=>asset.atlasRect={x:index*32,y:0,width:32,height:32});
manifest.atlas={file:'../../app/sprites/atlas.png',width:sprites.length*32,height:32,order:sprites.map(asset=>asset.id),sha256:createHash('sha256').update(readFileSync(atlas)).digest('hex'),bytes:readFileSync(atlas).length};
manifest.export.transparentPaddingToSquare=true;
writeComplete(resolve(root,'app/sprites/data.js'),'// Generated by scripts/build-sprites.mjs. Edit the artwork manifest and renderer source.\nconst PAULTENDO_SPRITE_DATA = '+encoded+';\n');
const start='    // BEGIN GENERATED SPRITES\n',end='    // END GENERATED SPRITES';
const target=resolve(root,'paultendo-mod.js');
let mod=readFileSync(target,'utf8');
const block=start+factory+'\n    const SPRITE_DATA = '+encoded+';\n    const spriteRenderer = createPaultendoSpriteRenderer(SPRITE_DATA);\n'+end;
if(mod.includes(start))mod=mod.slice(0,mod.indexOf(start))+block+mod.slice(mod.indexOf(end)+end.length);
else mod=mod.replace('    const dailyCaches = new WeakMap();',block+'\n    const dailyCaches = new WeakMap();');
writeComplete(target,mod);
writeComplete(manifestPath,JSON.stringify(manifest,null,2)+'\n');
console.log(`Embedded ${Object.keys(data.sprites).length} sprites and ${Object.keys(data.overlays).length} overlays (${encoded.length} bytes of indexed art).`);
